### ISSUE TITLE
command doesn't work. Return "Found invalid content-type

### ISSUE THREAD

**Issue by jared-bloomer** [leonardobdes/BIGREST#12]
When attempting to run device.command() i get Found invalid content-type no matter what the command is. Here is an example

```
>>> from pprint import pprint
>>> from bigrest.utils.utils import rest_format
>>> from f5lib import bigrest_login
>>> br = bigrest_login('myF5Device','','')[0]
>>> from bigrest.bigip import BIGIP
>>> cmd = {}
>>> cmd["command"] = "run"
>>> cmd["utilCmdArgs"] = "-c 'cat /VERSION'"
>>> pprint(cmd)
{'command': 'run', 'utilCmdArgs': "-c 'cat /VERSION'"}
>>> br.command("/mgmt/tm/util/bash", cmd)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bigrest/big.py", line 270, in command
    obj = self.create(path, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bigrest/big.py", line 186, in create
    raise RESTAPIError(response, self.debug)
bigrest.common.exceptions.RESTAPIError:
Status:
415
Response Body:
{
    "code": 415,
    "message": "Found invalid content-type. The content-type must be application/json. The received content-type is application/octet-stream",
    "errorStack": [],
    "apiError": 1
}
```

I don't see any way to adjust the content-type for the command method. Any advice?

**Comment by leonardobdes** [comment]
Sorry for the delay.
The SDK adds the content type internally, and it uses application/json almost everywhere, except in the download/upload methods.
So, the error is strange.

Can you access bash using that user via ssh?
Can you try with admin user using the SDK?
Bash is restricted for some user roles, so that is what I am looking for here.

If that is not the problem, please use the debug option.
[https://bigrest.readthedocs.io/bigip.html](https://bigrest.readthedocs.io/bigip.html)
That will include the full request and response, so it will make more clear what is the problem.
After you remove any confidential information, paste the content of the file here.

**Comment by leonardobdes** [comment]
Closing, no response.
