### ISSUE TITLE
BIGIP module creates a token on the F5 even when `request_token` is set to `False`

### ISSUE THREAD

**Issue by mitrajparmar93** [leonardobdes/BIGREST#13]
I have written a connection class using the following method:

```
def f5_conn(f5ip: str) -> BIGIP:
    """Function to create a connection to f5"""
    try:
        return BIGIP(device=f5ip, username=secrets["f5Username"], password=secrets["f5Password"], login_provider="tmos", request_token=False)
```

The above class gets invoked every time there is an API request to the F5 device.
We saw an error in our API that said:

`"user xxxx-xxxx-xxxx-xxxx-xxxxxxxx has reached maximum active login tokens"`

So, I decided to delete all tokens using a `DELETE` call to the `/mgmt/shared/authz/tokens` endpoint and then making sure `request_token` was set to `False`

Once I made a simple `GET` call to the device, I notice the device is still issuing tokens for that user.

**Comment by leonardobdes** [comment]
Fixed in version 1.4.0.

When you create the object BIGIP, the SDK is internally calling the method `_connect`.
This is just to test the connection.
The problem was that for basic authentication (username/password), the SDK was wrongly calling `/mgmt/shared/authn/login` for test, and that generates a token for each new object.
It is now using `/mgmt/shared/echo-query`, which validates the connection and does not generate a token.
