### ISSUE TITLE
Enhance debug functionality

### ISSUE THREAD

**Issue by f5-rahm** [leonardobdes/BIGREST#2]
Add ability to see curl format of every request sent as a list item in a debug attribute, whether or not there is an error.

Requires no change to the debug='file' submission, but will take that and:

- Set debug attribute to True
- Set debug_file attribute to the filename
- Append all requests as curl formatted commands to debug_output list attribute
- Still allow for debug file to be created on errors

**Comment by leonardobdes** [comment]
I looked at your implementaiton but there are 2 problems with this approach.
If we save every HTTP request in a curl format, we will use a lot of memory if the script is changing many objects or sending large files.
I tried to implement an option that would allow the user to get the curl command for the last HTTP request, but the problem is that the SDK does a lot of requests in the same method, so users would only see the last request for that method.
I end up adding the curl command to the output of the debug option, together with the information that already existed, and moved the debug functions to a separated file.
